SET FOREIGN_KEY_CHECKS = 0;
USE raquel_hris;

-- ============================================
-- 1. SEED RANK CATEGORIES
-- ============================================

-- Insert rank categories
INSERT INTO rank_categories (rank_category_id, rank_name, level_order) VALUES
(1, 'Executives', 1),
(2, 'Management Team', 2),
(3, 'Manager', 3),
(4, 'Supervisor', 4),
(5, 'R&F', 5);

-- ============================================
-- 2. SEED JOB TITLES
-- ============================================

-- Insert job titles with rank categorization and department assignment
-- Department IDs: 1=Acquired Properties, 2=Audit, 3=Business Development, 4=Compliance,
--                 5=General Services, 6=Human Resources, 7=IT, 8=Marketing, 9=Operations,
--                 10=Office of the President, 11=Purchasing, 12=Sales, 13=Treasury,
--                 14=Finance, 15=Accounting, 16=Construction/Maintenance
INSERT INTO job_titles (job_title, rank_category_id, department_id) VALUES
-- Office of the President
('President and CEO', 1, 10),
('General Manager', 2, 10),
('Executive Assistant I', 5, 10),
('Executive Assistant II', 5, 10),
('Executive Assistant on Training', 5, 10),
('Executive Secretary', 5, 10),
('OIC Executive Secretary', 5, 10),
('Reliever-Executive Assistant', 5, 10),

-- Finance
('VP for Finance', 1, 14),

-- Accounting
('VP for Comptrollership and Budget concurrent Accounting Manager', 1, 15),
('Accounting Head', 3, 15),
('OIC Accounting Head', 3, 15),
('Accounting Supervisor I', 4, 15),
('Accounting Supervisor II', 4, 15),
('Accounting Supervisor III', 4, 15),
('Accounting Supervisor on Training', 4, 15),
('Accounting Staff', 5, 15),
('Accounting Staff I', 5, 15),
('Accounting Staff II', 5, 15),
('Accounting Staff IV', 5, 15),
('Accounting Staff on Probation', 5, 15),
('PB-Accounting Staff', 5, 15),
('Senior Accounting Staff', 5, 15),

-- Acquired Properties
('VP for Acquired Properties', 1, 1),
('AP Manager I', 3, 1),
('AP Manager II', 3, 1),
('AP Manager III', 3, 1),
('Assistant AP Manager', 3, 1),
('AP Supervisor', 4, 1),
('AP Supervisor I', 4, 1),
('AP Supervisor II', 4, 1),
('AP Supervisor III', 4, 1),
('AP Supervisor on Training', 4, 1),
('Acquired Properties Department - AP Staff for Coordination and Communication I', 5, 1),
('Acquired Properties Officer', 5, 1),
('AP Encoder', 5, 1),
('AP Staff for Property Acquisition and Quality Control 1 on Training', 5, 1),
('AP Staff for Property Acquisition and Quality Control I', 5, 1),
('AP Staff for Property Acquisition and Quality Control II', 5, 1),
('AP Staff for Property Acquisition and Quality Control II on Training', 5, 1),
('AP Staff for Property Acquisition and Quality Control III', 5, 1),
('AP Staff for Vault Management I', 5, 1),
('AP Staff I', 5, 1),
('AP Staff II', 5, 1),
('AP Staff II on Training', 5, 1),
('AP Staff III', 5, 1),
('AP Staff IV', 5, 1),
('AP Staff on Probation', 5, 1),
('AP Staff on Training', 5, 1),
('AP Staff V', 5, 1),
('Appraiser', 5, 1),
('Appraiser on Probation', 5, 1),
('Junior AP Staff', 5, 1),
('Junior AP Staff on Training', 5, 1),
('OIC Appraiser', 5, 1),
('OIC Vault Custodian', 5, 1),
('Senior AP Staff', 5, 1),
('Vault Custodian', 5, 1),

-- Audit
('Audit Manager', 3, 2),
('Audit Manager I', 3, 2),
('Audit Manager II', 3, 2),
('Audit Manager III', 3, 2),
('Audit Supervisor', 4, 2),
('Audit Supervisor I', 4, 2),
('Audit Supervisor II', 4, 2),
('Audit Supervisor III', 4, 2),
('Audit Supervisor on Training', 4, 2),
('Auditor', 5, 2),
('Auditor I', 5, 2),
('Auditor II', 5, 2),
('Auditor III', 5, 2),
('Auditor IV', 5, 2),
('Auditor V', 5, 2),
('Auditor on Probation', 5, 2),
('Auditor on Training', 5, 2),
('Branch Auditor', 5, 2),
('Junior Auditor', 5, 2),
('OIC Auditor', 5, 2),
('OIC Branch/Department Auditor', 5, 2),
('Senior Auditor', 5, 2),

-- Business Development
('Business Development Officer', 5, 3),
('Business Development Staff', 5, 3),
('Business Development Staff I', 5, 3),
('Business Development Staff on Training', 5, 3),
('Marketing Officer for Business Development', 5, 3),
('OIC Marketing Officer for Business Development', 5, 3),

-- Compliance
('Compliance Manager I', 3, 4),
('Compliance Manager on Training', 3, 4),
('Compliance Supervisor', 4, 4),
('Compliance Officer', 5, 4),
('Compliance Staff I', 5, 4),
('Compliance Staff II', 5, 4),
('Compliance Staff III', 5, 4),
('Compliance Staff on Probation', 5, 4),
('Compliance Staff on Training', 5, 4),

-- General Services
('VP for General Services', 1, 5),
('GS Manager I', 3, 5),
('GS Manager II', 3, 5),
('GS Manager III', 3, 5),
('GS Manager IV', 3, 5),
('GS Supervisor I', 4, 5),
('GS Supervisor IV', 4, 5),
('Driver I', 5, 5),
('Driver II', 5, 5),
('Driver III', 5, 5),
('Driver V', 5, 5),
('Driver on Probation', 5, 5),
('Facilities Maintenance Staff on Probation', 5, 5),
('General Services Staff', 5, 5),
('GSD Staff', 5, 5),
('Inventory Staff I', 5, 5),
('Inventory Staff on Probation', 5, 5),
('Janitor', 5, 5),
('Maintenance Staff', 5, 5),
('Maintenance Staff on Probation', 5, 5),
('Messenger', 5, 5),
('Messenger I', 5, 5),
('Messenger II', 5, 5),
('Messenger on Probation', 5, 5),
('Security Monitoring Staff', 5, 5),
('Security Monitoring Staff ', 5, 5),
('Security Monitoring Staff I', 5, 5),
('Security Monitoring Staff II', 5, 5),
('Security Monitoring Staff III', 5, 5),
('Security Monitoring Staff IV', 5, 5),
('Security Monitoring Staff on Probation', 5, 5),
('Warehouse Staff I', 5, 5),
('Warehouse Staff I on Training', 5, 5),
('Warehouse Staff on Probation', 5, 5),

-- Human Resources
('HR Manager', 3, 6),
('HR Manager I', 3, 6),
('HR Manager II', 3, 6),
('HR Manager III', 3, 6),
('HR Manager IV', 3, 6),
('OIC HR Manager', 3, 6),
('HR Supervisor', 4, 6),
('HR Supervisor I', 4, 6),
('HR Supervisor II', 4, 6),
('HR Supervisor III', 4, 6),
('HR Supervisor IV', 4, 6),
('HR Staff', 5, 6),
('HR Staff - Compensation and Benefit', 5, 6),
('HR Staff I', 5, 6),
('HR Staff II', 5, 6),
('HR Staff II on Training', 5, 6),
('HR Staff III', 5, 6),
('HR Staff IV', 5, 6),
('HR Staff on Probation', 5, 6),

-- Information Technology
('IT Manager I', 3, 7),
('IT Manager II', 3, 7),
('IT Manager III', 3, 7),
('IT Manager IV', 3, 7),
('IT Supervisor', 4, 7),
('IT Supervisor I', 4, 7),
('IT Supervisor II', 4, 7),
('IT Supervisor III', 4, 7),
('IT Supervisor IV', 4, 7),
('IT Supervisor V', 4, 7),
('Help Desk Assistant', 5, 7),
('Help Desk Assistant for Auxiliary II', 5, 7),
('Help Desk Assistant for Auxiliary III', 5, 7),
('Help Desk Assistant I', 5, 7),
('Help Desk Assistant on Probation', 5, 7),
('Helpdesk Assistant I', 5, 7),
('Helpdesk Assistant III', 5, 7),
('Programmer I', 5, 7),
('Programmer on Probation', 5, 7),
('System Programmer', 5, 7),
('Tech Support Staff I', 5, 7),
('Tech Support Staff on Probation', 5, 7),
('Technical Support Assistant', 5, 7),
('Technical Support Staff I', 5, 7),
('Technical Support Staff II', 5, 7),
('Technical Support Staff III', 5, 7),
('Technical Support Staff IV', 5, 7),
('Technical Support Staff V', 5, 7),
('Technical Support Staff on Probation', 5, 7),

-- Marketing
('Marketing Manager', 3, 8),
('Marketing Manager I', 3, 8),
('Marketing Manager II', 3, 8),
('Marketing Manager on Training', 3, 8),
('Marketing Supervisor I', 4, 8),
('Marketing Supervisor II', 4, 8),
('Marketing Supervisor on Training', 4, 8),
('Marketing Staff', 5, 8),
('Marketing Staff I', 5, 8),
('Marketing Staff II', 5, 8),
('Marketing Staff on Probatio', 5, 8),
('Marketing Staff on Probation', 5, 8),
('Marketing Staff on Training', 5, 8),
('Marketing Staff- Price Strategy, Product Development and Customer Relation 2', 5, 8),
('Marketing Staff-Trainee Operations', 5, 8),

-- Operations
('VP for Operations', 1, 9),
('Operations Manager', 3, 9),
('Regional Manager I', 3, 9),
('Regional Manager II', 3, 9),
('Regional Manager on Training', 3, 9),
('Area Coordinator', 4, 9),
('Area Coordinator I', 4, 9),
('Area Coordinator I on Training', 4, 9),
('Area Coordinator II', 4, 9),
('Area Coordinator on Training', 4, 9),
('Area Supervisor I', 4, 9),
('Area Supervisor II', 4, 9),
('Area Supervisor on Training', 4, 9),
('Operations Supervisor', 4, 9),
('Operations Supervisor on Training', 4, 9),
('Acting Area Officer', 5, 9),
('Area Coortinator on Training', 5, 9),
('Area Officer', 5, 9),
('Branch Staff', 5, 9),
('Branch Staff ', 5, 9),
('Branch Staff I', 5, 9),
('Branch Staff II', 5, 9),
('Branch Staff III', 5, 9),
('Branch Staff IV', 5, 9),
('Branch Staff on Probation', 5, 9),
('Focal Person I', 5, 9),
('Focal Person II', 5, 9),
('Focal Person III', 5, 9),
('Focal Person IV', 5, 9),
('Focal Person V', 5, 9),
('Operations Coordinator', 5, 9),

-- Purchasing
('Purchasing Supervisor', 4, 11),
('Purchasing Supervisor II', 4, 11),
('Purchasing Supervisor III', 4, 11),
('Purchasing Supervisor on Training', 4, 11),
('Purchasing Officer', 5, 11),
('Purchasing Staff', 5, 11),
('Purchasing Staff I', 5, 11),
('Purchasing Staff II', 5, 11),
('Purchasing Staff on Probation', 5, 11),
('Purchasing Staff on Training', 5, 11),

-- Sales
('OIC Auction Sales Supervisor', 4, 12),
('Sales Associate', 5, 12),
('Sales Associate I', 5, 12),
('Sales Associate II', 5, 12),
('Sales Associate II on Training', 5, 12),
('Sales Associate III', 5, 12),
('Sales Associate on Probation', 5, 12),
('Sales Clerk', 5, 12),
('Sales Clerk II', 5, 12),
('Sales Clerk II on Training', 5, 12),
('Sales Staff', 5, 12),

-- Treasury
('Treasury Supervisor I', 3, 13),
('Treasury Supervisor II', 3, 13),
('Treasury Supervisor III', 3, 13),
('Treasury Supervisor IV', 3, 13),
('PB Treasury Staff', 5, 13),
('Treasury Officer', 5, 13),
('Treasury Staff I', 5, 13),
('Treasury Staff on Probation', 5, 13),
('Treasury Staff on Training', 5, 13),

-- Construction / Maintenance
('Construction and Maintenance', 5, 16),
('Construction and Maintenance on Probatio', 5, 16),
('Construction and Maintenance Staff I', 5, 16),
('Construction and Maintenance Staff II', 5, 16),
('Construction and Maintenance Staff III', 5, 16),
('Construction and Maintenance Staff on Probation', 5, 16),

-- General / Uncategorized
('VP for Management Services', 1, NULL),
('Assistant Manager - CorPlan', 3, NULL),
('Cafe Supervisor', 4, NULL),
('Administrative Staff', 5, NULL),
('Administrative Staff I', 5, NULL),
('Administrative Staff on Training', 5, NULL),
('Management Trainee', 5, NULL),
('OJT', 5, NULL),
('Immediate Head', 3, NULL),
('Cashier', 5, NULL);


-- =============================================================
-- 1. CLEANUP NO NEED TO DROP ENTIRE DATABASE JUST TO RESET
-- =============================================================
DELETE FROM `employee_references`; ALTER TABLE `employee_references` AUTO_INCREMENT = 1;
DELETE FROM `employee_liabilities`; ALTER TABLE `employee_liabilities` AUTO_INCREMENT = 1;
DELETE FROM `employee_personal_properties`; ALTER TABLE `employee_personal_properties` AUTO_INCREMENT = 1;
DELETE FROM `employee_real_properties`; ALTER TABLE `employee_real_properties` AUTO_INCREMENT = 1;
DELETE FROM `employee_memberships`; ALTER TABLE `employee_memberships` AUTO_INCREMENT = 1;
DELETE FROM `employee_recognitions`; ALTER TABLE `employee_recognitions` AUTO_INCREMENT = 1;
DELETE FROM `employee_skills`; ALTER TABLE `employee_skills` AUTO_INCREMENT = 1;
DELETE FROM `employee_eligibility`; ALTER TABLE `employee_eligibility` AUTO_INCREMENT = 1;
DELETE FROM `employee_voluntary_work`; ALTER TABLE `employee_voluntary_work` AUTO_INCREMENT = 1;
DELETE FROM `employee_trainings`; ALTER TABLE `employee_trainings` AUTO_INCREMENT = 1;
DELETE FROM `employee_work_experience`; ALTER TABLE `employee_work_experience` AUTO_INCREMENT = 1;
DELETE FROM `employee_education`; ALTER TABLE `employee_education` AUTO_INCREMENT = 1;
DELETE FROM `employee_siblings`; ALTER TABLE `employee_siblings` AUTO_INCREMENT = 1;
DELETE FROM `employee_children`; ALTER TABLE `employee_children` AUTO_INCREMENT = 1;
DELETE FROM `employee_family`; ALTER TABLE `employee_family` AUTO_INCREMENT = 1;
DELETE FROM `employee_disclosures`; ALTER TABLE `employee_disclosures` AUTO_INCREMENT = 1;
DELETE FROM `employee_government_ids`; ALTER TABLE `employee_government_ids` AUTO_INCREMENT = 1;
DELETE FROM `employee_details`; ALTER TABLE `employee_details` AUTO_INCREMENT = 1;
DELETE FROM `employee_emergency_contacts`; ALTER TABLE `employee_emergency_contacts` AUTO_INCREMENT = 1;
DELETE FROM `employee_contacts`; ALTER TABLE `employee_contacts` AUTO_INCREMENT = 1;
DELETE FROM `employee_addresses`; ALTER TABLE `employee_addresses` AUTO_INCREMENT = 1;
-- DELETE FROM `users`; ALTER TABLE `users` AUTO_INCREMENT = 1;
DELETE FROM `employees`; ALTER TABLE `employees` AUTO_INCREMENT = 1;
DELETE FROM `departments`; ALTER TABLE `departments` AUTO_INCREMENT = 1;
DELETE FROM `branches`; ALTER TABLE `branches` AUTO_INCREMENT = 1;

-- ============================================
-- 2. BRANCHES
-- ============================================
INSERT INTO `branches` (`branch_id`, `branch_name`, `location`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1,'Agdangan', 'Agdangan, Quezon', 1, NOW(), NOW(), NULL),
(2,'Alabat', 'Alabat, Quezon', 1, NOW(), NOW(), NULL),
(3,'Alaminos', 'Alaminos, Pangasinan', 1, NOW(), NOW(), NULL),
(4,'Angono', 'Angono, Rizal', 1, NOW(), NOW(), NULL),
(5,'Angono 1', 'Angono 1, Rizal', 1, NOW(), NOW(), NULL),
(6,'Angono 2', 'Angono 2, Rizal', 1, NOW(), NOW(), NULL),
(7,'Angono2', 'Angono 2, Rizal', 1, NOW(), NOW(), NULL),
(8,'Antipolo 2', 'Antipolo 2, Rizal', 1, NOW(), NOW(), NULL),
(9,'Antipolo 3', 'Antipolo 3, Rizal', 1, NOW(), NOW(), NULL),
(10,'Apalit', 'Apalit, Pampanga', 1, NOW(), NOW(), NULL),
(11,'Apalit 1', 'Apalit 1, Pampanga', 1, NOW(), NOW(), NULL),
(12,'Apalit 2', 'Apalit 2, Pampanga', 1, NOW(), NOW(), NULL),
(13,'Atimonan', 'Atimonan, Quezon', 1, NOW(), NOW(), NULL),
(14,'Atimonan 1', 'Atimonan 1, Quezon', 1, NOW(), NOW(), NULL),
(15,'Atimonan 2', 'Atimonan 2, Quezon', 1, NOW(), NOW(), NULL),
(16,'Atimonan1', 'Atimonan 1, Quezon', 1, NOW(), NOW(), NULL),
(17,'Atimonan2', 'Atimonan 2, Quezon', 1, NOW(), NOW(), NULL),
(18,'Aura Jewel', 'Aura Jewel', 1, NOW(), NOW(), NULL),
(19,'Bacoor', 'Bacoor, Cavite', 1, NOW(), NOW(), NULL),
(20,'Balayan', 'Balayan, Batangas', 1, NOW(), NOW(), NULL),
(21,'Banilad', 'Banilad', 1, NOW(), NOW(), NULL),
(22,'Baras', 'Baras, Rizal', 1, NOW(), NOW(), NULL),
(23,'Bauan', 'Bauan, Batangas', 1, NOW(), NOW(), NULL),
(24,'Biñan', 'Biñan, Laguna', 1, NOW(), NOW(), NULL),
(25,'Binangonan', 'Binangonan, Rizal', 1, NOW(), NOW(), NULL),
(26,'Binangonan 3', 'Binangonan 3, Rizal', 1, NOW(), NOW(), NULL),
(27,'Binangonan2', 'Binangonan 2, Rizal', 1, NOW(), NOW(), NULL),
(28,'Boac', 'Boac, Marinduque', 1, NOW(), NOW(), NULL),
(29,'Butuan', 'Butuan, Agusan del Norte', 1, NOW(), NOW(), NULL),
(30,'Butuan 1', 'Butuan 1, Agusan del Norte', 1, NOW(), NOW(), NULL),
(31,'Cabana', 'Cabana', 1, NOW(), NOW(), NULL),
(32,'Cabuyao 1', 'Cabuyao 1, Laguna', 1, NOW(), NOW(), NULL),
(33,'Cabuyao 2', 'Cabuyao 2, Laguna', 1, NOW(), NOW(), NULL),
(34,'Cabuyao 3', 'Cabuyao 3, Laguna', 1, NOW(), NOW(), NULL),
(35,'Cabuyao1', 'Cabuyao 1, Laguna', 1, NOW(), NOW(), NULL),
(36,'Cabuyao2', 'Cabuyao 2, Laguna', 1, NOW(), NOW(), NULL),
(37,'Cabuyao3', 'Cabuyao 3, Laguna', 1, NOW(), NOW(), NULL),
(38,'Cainta', 'Cainta, Rizal', 1, NOW(), NOW(), NULL),
(39,'Calamba 1', 'Calamba 1, Laguna', 1, NOW(), NOW(), NULL),
(40,'Calamba1', 'Calamba 1, Laguna', 1, NOW(), NOW(), NULL),
(41,'Calamba2', 'Calamba 2, Laguna', 1, NOW(), NOW(), NULL),
(42,'Calatagan', 'Calatagan, Batangas', 1, NOW(), NOW(), NULL),
(43,'Calauag', 'Calauag, Quezon', 1, NOW(), NOW(), NULL),
(44,'Calauan', 'Calauan, Laguna', 1, NOW(), NOW(), NULL),
(45,'Candelaria 1', 'Candelaria 1, Quezon', 1, NOW(), NOW(), NULL),
(46,'Candelaria 2', 'Candelaria 2, Quezon', 1, NOW(), NOW(), NULL),
(47,'Candelaria1', 'Candelaria 1, Quezon', 1, NOW(), NOW(), NULL),
(48,'Candelaria2', 'Candelaria 2, Quezon', 1, NOW(), NOW(), NULL),
(49,'Carmona', 'Carmona, Cavite', 1, NOW(), NOW(), NULL),
(50,'Catanauan', 'Catanauan, Quezon', 1, NOW(), NOW(), NULL),
(51,'Cav City', 'Cavite City', 1, NOW(), NOW(), NULL),
(52,'Cavite City', 'Cavite City', 1, NOW(), NOW(), NULL),
(53,'CDO 1', 'Cagayan de Oro 1', 1, NOW(), NOW(), NULL),
(54,'CDO 3', 'Cagayan de Oro 3', 1, NOW(), NOW(), NULL),
(55,'Celer', 'Celer', 1, NOW(), NOW(), NULL),
(56,'CM Recto', 'CM Recto', 1, NOW(), NOW(), NULL),
(57,'Commonwealth', 'Commonwealth, Quezon City', 1, NOW(), NOW(), NULL),
(58,'Compliance', 'Compliance Department', 1, NOW(), NOW(), NULL),
(59,'CU', 'Credit Union', 1, NOW(), NOW(), NULL),
(60,'Cuenca', 'Cuenca, Batangas', 1, NOW(), NOW(), NULL),
(61,'Daet', 'Daet, Camarines Norte', 1, NOW(), NOW(), NULL),
(62,'Daet 2', 'Daet 2, Camarines Norte', 1, NOW(), NOW(), NULL),
(63,'Dalahican', 'Dalahican, Quezon', 1, NOW(), NOW(), NULL),
(64,'Dasmarinas', 'Dasmariñas, Cavite', 1, NOW(), NOW(), NULL),
(65,'Dasmariñas', 'Dasmariñas, Cavite', 1, NOW(), NOW(), NULL),
(66,'Dolores', 'Dolores, Quezon', 1, NOW(), NOW(), NULL),
(67,'Enriquez', 'Enriquez', 1, NOW(), NOW(), NULL),
(68,'General Trias 1', 'General Trias 1, Cavite', 1, NOW(), NOW(), NULL),
(69,'General Trias 2', 'General Trias 2, Cavite', 1, NOW(), NOW(), NULL),
(70,'GMA', 'GMA', 1, NOW(), NOW(), NULL),
(71,'Gomez', 'Gomez', 1, NOW(), NOW(), NULL),
(72,'Guinyangan', 'Guinyangan, Quezon', 1, NOW(), NOW(), NULL),
(73,'Gulang-Gulang', 'Gulang-Gulang, Quezon', 1, NOW(), NOW(), NULL),
(74,'Gumaca', 'Gumaca, Quezon', 1, NOW(), NOW(), NULL),
(75,'Indang', 'Indang, Cavite', 1, NOW(), NOW(), NULL),
(76,'Infanta', 'Infanta, Quezon', 1, NOW(), NOW(), NULL),
(77,'Iyam', 'Iyam', 1, NOW(), NOW(), NULL),
(78,'Kawit', 'Kawit, Cavite', 1, NOW(), NOW(), NULL),
(79,'Labangon 2', 'Labangon 2, Cebu', 1, NOW(), NOW(), NULL),
(80,'Lapasan', 'Lapasan, Cagayan de Oro', 1, NOW(), NOW(), NULL),
(81,'Lapu-Lapu', 'Lapu-Lapu, Cebu', 1, NOW(), NOW(), NULL),
(82,'Lapu-Lapu 1', 'Lapu-Lapu 1, Cebu', 1, NOW(), NOW(), NULL),
(83,'Lapu-Lapu 2', 'Lapu-Lapu 2, Cebu', 1, NOW(), NOW(), NULL),
(84,'Las Piñas2', 'Las Piñas 2, Metro Manila', 1, NOW(), NOW(), NULL),
(85,'Laurel', 'Laurel, Batangas', 1, NOW(), NOW(), NULL),
(86,'Lemery', 'Lemery, Batangas', 1, NOW(), NOW(), NULL),
(87,'Lian', 'Lian, Batangas', 1, NOW(), NOW(), NULL),
(88,'Liliw', 'Liliw, Laguna', 1, NOW(), NOW(), NULL),
(89,'Lipa 1', 'Lipa 1, Batangas', 1, NOW(), NOW(), NULL),
(90,'Lipa TM Kalaw', 'Lipa TM Kalaw, Batangas', 1, NOW(), NOW(), NULL),
(91,'Lipa1', 'Lipa 1, Batangas', 1, NOW(), NOW(), NULL),
(92,'Lopez', 'Lopez, Quezon', 1, NOW(), NOW(), NULL),
(93,'Los Baños', 'Los Baños, Laguna', 1, NOW(), NOW(), NULL),
(94,'Lubao', 'Lubao, Pampanga', 1, NOW(), NOW(), NULL),
(95,'Lucban 1', 'Lucban 1, Quezon', 1, NOW(), NOW(), NULL),
(96,'Lucban 2', 'Lucban 2, Quezon', 1, NOW(), NOW(), NULL),
(97,'Lucban1', 'Lucban 1, Quezon', 1, NOW(), NOW(), NULL),
(98,'Luisiana', 'Luisiana, Laguna', 1, NOW(), NOW(), NULL),
(99,'Lumban', 'Lumban, Laguna', 1, NOW(), NOW(), NULL),
(100,'Macalelon', 'Macalelon, Quezon', 1, NOW(), NOW(), NULL),
(101,'Magdalena', 'Magdalena, Laguna', 1, NOW(), NOW(), NULL),
(102,'Raquel Pawnshop Main Office', 'RGC Building, Diversion Road, Sitio 1 Barangay Mayuwi Tayabas City', 1, NOW(), NOW(), NULL),
(103,'Majayjay', 'Majayjay, Laguna', 1, NOW(), NOW(), NULL),
(104,'Mataas na Kahoy', 'Mataas na Kahoy, Batangas', 1, NOW(), NOW(), NULL),
(105,'Mauban', 'Mauban, Quezon', 1, NOW(), NOW(), NULL),
(106,'Mendez', 'Mendez, Cavite', 1, NOW(), NOW(), NULL),
(107,'Mercedes', 'Mercedes, Camarines Norte', 1, NOW(), NOW(), NULL),
(108,'Merchan', 'Merchan', 1, NOW(), NOW(), NULL),
(109,'Mogpog', 'Mogpog, Marinduque', 1, NOW(), NOW(), NULL),
(110,'Morong', 'Morong, Rizal', 1, NOW(), NOW(), NULL),
(111,'Mulanay', 'Mulanay, Quezon', 1, NOW(), NOW(), NULL),
(112,'Muntinlupa 1', 'Muntinlupa 1, Metro Manila', 1, NOW(), NOW(), NULL),
(113,'Muntinlupa 2', 'Muntinlupa 2, Metro Manila', 1, NOW(), NOW(), NULL),
(114,'Muntinlupa 3', 'Muntinlupa 3, Metro Manila', 1, NOW(), NOW(), NULL),
(115,'Nagcarlan', 'Nagcarlan, Laguna', 1, NOW(), NOW(), NULL),
(116,'Naic', 'Naic, Cavite', 1, NOW(), NOW(), NULL),
(117,'Nasugbu', 'Nasugbu, Batangas', 1, NOW(), NOW(), NULL),
(118,'Obando', 'Obando, Bulacan', 1, NOW(), NOW(), NULL),
(119,'Pacita', 'Pacita, San Pedro, Laguna', 1, NOW(), NOW(), NULL),
(120,'Paete', 'Paete, Laguna', 1, NOW(), NOW(), NULL),
(121,'Pagbilao', 'Pagbilao, Quezon', 1, NOW(), NOW(), NULL),
(122,'Pagbilao 1', 'Pagbilao 1, Quezon', 1, NOW(), NOW(), NULL),
(123,'Pagbilao2', 'Pagbilao 2, Quezon', 1, NOW(), NOW(), NULL),
(124,'Pagsanjan', 'Pagsanjan, Laguna', 1, NOW(), NOW(), NULL),
(125,'Paracale', 'Paracale, Camarines Norte', 1, NOW(), NOW(), NULL),
(126,'Paranaque', 'Parañaque, Metro Manila', 1, NOW(), NOW(), NULL),
(127,'Pasig', 'Pasig, Metro Manila', 1, NOW(), NOW(), NULL),
(128,'Pasig 1', 'Pasig 1, Metro Manila', 1, NOW(), NOW(), NULL),
(129,'Peraquel', 'Peraquel', 1, NOW(), NOW(), NULL),
(130,'Perez', 'Perez, Quezon', 1, NOW(), NOW(), NULL),
(131,'Pililla', 'Pililla, Rizal', 1, NOW(), NOW(), NULL),
(132,'Plaridel', 'Plaridel, Bulacan', 1, NOW(), NOW(), NULL),
(133,'Profugo', 'Profugo', 1, NOW(), NOW(), NULL),
(134,'Quezon Avenue', 'Quezon Avenue, Quezon City', 1, NOW(), NOW(), NULL),
(135,'Real', 'Real, Quezon', 1, NOW(), NOW(), NULL),
(136,'Relaxa', 'Relaxa', 1, NOW(), NOW(), NULL),
(137,'Retiro', 'Retiro', 1, NOW(), NOW(), NULL),
(138,'Rodriguez', 'Rodriguez, Rizal', 1, NOW(), NOW(), NULL),
(139,'Rosario', 'Rosario, Batangas', 1, NOW(), NOW(), NULL),
(140,'Rosario, Bats.', 'Rosario, Batangas', 1, NOW(), NOW(), NULL),
(141,'RPI', 'Raquel Pawnshop Inc.', 1, NOW(), NOW(), NULL),
(142,'RPI-WU', 'RPI - Western Union', 1, NOW(), NOW(), NULL),
(143,'RTA', 'RTA', 1, NOW(), NOW(), NULL),
(144,'RTIUM', 'RTIUM', 1, NOW(), NOW(), NULL),
(145,'San Andres', 'San Andres, Quezon', 1, NOW(), NOW(), NULL),
(146,'San Francisco', 'San Francisco, Quezon', 1, NOW(), NOW(), NULL),
(147,'San Juan', 'San Juan, Metro Manila', 1, NOW(), NOW(), NULL),
(148,'San Mateo 2', 'San Mateo 2, Rizal', 1, NOW(), NOW(), NULL),
(149,'San Mateo Banaba', 'San Mateo Banaba, Rizal', 1, NOW(), NOW(), NULL),
(150,'San Narciso', 'San Narciso, Quezon', 1, NOW(), NOW(), NULL),
(151,'San Pablo', 'San Pablo, Laguna', 1, NOW(), NOW(), NULL),
(152,'San Pascual', 'San Pascual, Batangas', 1, NOW(), NOW(), NULL),
(153,'San Pedro', 'San Pedro, Laguna', 1, NOW(), NOW(), NULL),
(154,'Sariaya', 'Sariaya, Quezon', 1, NOW(), NOW(), NULL),
(155,'Sariaya 1', 'Sariaya 1, Quezon', 1, NOW(), NOW(), NULL),
(156,'Sariaya 2', 'Sariaya 2, Quezon', 1, NOW(), NOW(), NULL),
(157,'Sariaya1', 'Sariaya 1, Quezon', 1, NOW(), NOW(), NULL),
(158,'Sariaya2', 'Sariaya 2, Quezon', 1, NOW(), NOW(), NULL),
(159,'Silang', 'Silang, Cavite', 1, NOW(), NOW(), NULL),
(160,'Siniloan', 'Siniloan, Laguna', 1, NOW(), NOW(), NULL),
(161,'Sta Maria', 'Santa Maria, Laguna', 1, NOW(), NOW(), NULL),
(162,'Sta. Cruz M.', 'Santa Cruz, Marinduque', 1, NOW(), NOW(), NULL),
(163,'Sta. Elena', 'Santa Elena, Laguna', 1, NOW(), NOW(), NULL),
(164,'Sta. Maria', 'Santa Maria, Laguna', 1, NOW(), NOW(), NULL),
(165,'Sta. Rosa', 'Santa Rosa, Laguna', 1, NOW(), NOW(), NULL),
(166,'Sta. Rosa 1', 'Santa Rosa 1, Laguna', 1, NOW(), NOW(), NULL),
(167,'Sta.Rosa', 'Santa Rosa, Laguna', 1, NOW(), NOW(), NULL),
(168,'Sto. Tomas', 'Santo Tomas, Batangas', 1, NOW(), NOW(), NULL),
(169,'Taal', 'Taal, Batangas', 1, NOW(), NOW(), NULL),
(170,'Tagkawayan', 'Tagkawayan, Quezon', 1, NOW(), NOW(), NULL),
(171,'Talipan', 'Talipan, Quezon', 1, NOW(), NOW(), NULL),
(172,'Talisay', 'Talisay, Batangas', 1, NOW(), NOW(), NULL),
(173,'Tanauan', 'Tanauan, Batangas', 1, NOW(), NOW(), NULL),
(174,'Tanay', 'Tanay, Rizal', 1, NOW(), NOW(), NULL),
(175,'Tanay 1', 'Tanay 1, Rizal', 1, NOW(), NOW(), NULL),
(176,'Tanza', 'Tanza, Cavite', 1, NOW(), NOW(), NULL),
(177,'Tayabas 1', 'Tayabas 1, Quezon', 1, NOW(), NOW(), NULL),
(178,'Tayabas 2', 'Tayabas 2, Quezon', 1, NOW(), NOW(), NULL),
(179,'Tayabas1', 'Tayabas 1, Quezon', 1, NOW(), NOW(), NULL),
(180,'Tayabas2', 'Tayabas 2, Quezon', 1, NOW(), NOW(), NULL),
(181,'Taytay', 'Taytay, Rizal', 1, NOW(), NOW(), NULL),
(182,'Teresa', 'Teresa, Rizal', 1, NOW(), NOW(), NULL),
(183,'Ternate', 'Ternate, Cavite', 1, NOW(), NOW(), NULL),
(184,'Tiaong', 'Tiaong, Quezon', 1, NOW(), NOW(), NULL),
(185,'Trece Martires', 'Trece Martires, Cavite', 1, NOW(), NOW(), NULL),
(186,'Tuy', 'Tuy, Batangas', 1, NOW(), NOW(), NULL),
(187,'Unisan', 'Unisan, Quezon', 1, NOW(), NOW(), NULL),
(188,'Valencia 1', 'Valencia 1', 1, NOW(), NOW(), NULL),
(189,'Victoria', 'Victoria, Laguna', 1, NOW(), NOW(), NULL),
(190,'Vivus', 'Vivus', 1, NOW(), NOW(), NULL),
(191,'WU', 'Western Union', 1, NOW(), NOW(), NULL),
(192,'Zamora', 'Zamora', 1, NOW(), NOW(), NULL);
-- ============================================
-- 3. DEPARTMENTS
-- ============================================
INSERT INTO `departments` (`department_id`, `department_name`, `description`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'Acquired Properties', '', 1, NOW(), NOW(), NULL),
(2, 'Audit', '', 1, NOW(), NOW(), NULL),
(3, 'Business Development', '', 1, NOW(), NOW(), NULL),
(4, 'Compliance', '', 1, NOW(), NOW(), NULL),
(5, 'General Services', '', 1, NOW(), NOW(), NULL),
(6, 'Human Resources', '', 1, NOW(), NOW(), NULL),
(7, 'Information Technology', '', 1, NOW(), NOW(), NULL),
(8, 'Marketing', '', 1, NOW(), NOW(), NULL),
(9, 'Operations', '', 1, NOW(), NOW(), NULL),
(10, 'Office of the President', '', 1, NOW(), NOW(), NULL),
(11, 'Purchasing', '', 1, NOW(), NOW(), NULL),
(12, 'Sales', '', 1, NOW(), NOW(), NULL),
(13, 'Treasury', '', 1, NOW(), NOW(), NULL),
(14, 'Finance', '', 1, NOW(), NOW(), NULL),
(15, 'Accounting', '', 1, NOW(), NOW(), NULL),
(16, 'Construction', '', 1, NOW(), NOW(), NULL),
(17, 'Maintenance', '', 1, NOW(), NOW(), NULL);

SET FOREIGN_KEY_CHECKS = 1;